author: LINE Corporation
author_url: https://line.me
clean: true
github_url: https://github.com/line/line-sdk-ios-swift
hide_documentation_coverage: true
module: LineSDK
output: docs/internal
sdk: iphonesimulator
skip_undocumented: true
source_directory: LineSDK
theme: "jazzy-templates/linedevdocs"
