author: LINE Corporation
author_url: https://line.me
clean: true
github_url: https://github.com/line/line-sdk-ios-swift
hide_documentation_coverage: true
module: LineSDK
output: docs/public
sdk: iphonesimulator
skip_undocumented: true
source_directory: LineSDK
theme: "jazzy-templates/linedevdocs"
readme: REFERENCETOP.md
exclude: 
  - "LineSDK/LineSDK/Messaging/*"
  - "LineSDK/LineSDK/Graph/*"
  - "LineSDK/LineSDK/OpenChat/*"
  - "LineSDK/LineSDK/Networking/API/API+Internal.swift"
  - "LineSDK/LineSDK/LineSDKUI/SharingUI/*"
  - "LineSDK/LineSDK/Utils/Result.swift"