language: objective-c

addons:
  homebrew:
    packages:
    - carthage

osx_image: 
- xcode10.1
- xcode10.2

env:
- LANE=lint_pod
- LANE=lint_carthage


cache: bundler

before_install:
  - gem install bundler

script:
  - bundle exec fastlane $LANE
