language: objective-c

addons:
  homebrew:
    packages:
    - carthage

osx_image: 
- xcode10.1
- xcode10.2

env:
- LANE=lint_pod
- LANE=lint_pod_4.2

matrix:
  exclude:
    - osx_image: xcode10.1
      env: LANE=lint_pod

cache: bundler

before_install:
  - gem install bundler

script:
  - bundle exec fastlane $LANE
