default_platform(:ios)

platform :ios do

  before_all do
    xcversion(version: "9.4.1")
  end

  desc "Switch to Beta environment"
  lane :to_beta do
    Dir.chdir("../") do
      `git clone https://git.linecorp.com/wei-wang/linesdk-ios-swift-beta-config.git 2> /dev/null || (cd linesdk-ios-swift-beta-config ; git pull)`
    end

    env_path = Pathname.new("../LineSDK/LineSDK/Utils/URLs.swift")
    clone_path = Pathname.new("../linesdk-ios-swift-beta-config/URLs.swift")
    FileUtils.cp(clone_path, env_path)
  end

  desc "Run tests"
  lane :tests do
    run_tests(
        workspace: "LineSDK.xcworkspace",
        devices: ["iPhone 6s"],
        scheme: "LineSDK"
    )
  end

end
